services:
  - type: web
    name: oni-ai-frontend
    env: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html

  - type: web
    name: oni-ai-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
